baseURL = "https://abianche.github.io/"
languageCode = "en-us"
title = "Alessio Bianchetti"

DefaultContentLanguage = "en"

theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

# googleAnalytics = ""
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "abianche.github.io"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = true
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false
disableKinds = ["RSS", "sitemap", "404"]

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Alessio Bianchetti"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = ""

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Alessio Bianchetti profile page"
  keywords = "profile,software,development,programming,hugo,flutter"
  images = [""]

  profilePicture = "/images/profile.jpg"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = ""

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

  [params.logo]
    logoText     = "$ cd /home/"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/_abianche/"

  [[params.social]]
    name = "email"
    url  = "mailto:alessio.bianchetti@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/abianche/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/alessiobianchetti/"

  [[params.social]]
    name = "facebook"
    url = "https://www.facebook.com/alessio.bianchetti"

  [[params.social]]
    name = "credit-card"
    url = "https://paypal.me/abianche"

[languages]
  [languages.en]
    homeSubtitle = "Computer Scientist"
    subtitle  = "Profile"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.it]
    homeSubtitle = "Informatico"
    subtitle  = "Profilo"
    weight    = 2
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  # [languages.en.menu]
  #   [[languages.en.menu.main]]
  #     identifier = "about"
  #     name = "About"
  #     url = "about/"
  #   [[languages.en.menu.main]]
  #     identifier = "posts"
  #     name = "Posts"
  #     url = "posts/"
